name: Changelogs

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Change Log
        id: generate_log
        run: |
          curl -sf https://gobinaries.com/barelyhuman/commitlog | sh
          commitlog > CHANGELOG.md
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GH_TOKEN }}
